services:
  # Full-stack deployment - Flask serves both API and frontend
  - type: web
    name: school-store-app
    env: python
    buildCommand: chmod +x build.sh && ./build.sh && python school_store_backend/init_database.py
    startCommand: cd school_store_backend && gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 --access-logfile - --error-logfile - src.main:app
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: school-store-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: school-store-db
    databaseName: school_store
    user: school_store_user
    plan: Basic-256mb